version: "3.9"

services:
  timescaledb:
    build:
      context: ./      # repo/sigcomm-results
      dockerfile: Dockerfile
    container_name: timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: original_filtered
    ports:
      - "5432:5432"
    volumes:
      - tsdb_data:/var/lib/postgresql/data
      - ./dump:/dump
      - ./exports:/exports
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      timescaledb:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  tsdb_data:
  pgadmin_data: